BlogSystem.Web/Controllers/SidebarController.cs
namespace BlogSystem.Web.Controllers
{
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using BlogSystem.Data.Contracts;
    using BlogSystem.Data.Models;
    using BlogSystem.Services.Data;
    using BlogSystem.Web.ViewModels;
    using BlogSystem.Web.ViewModels.Videos;

    public class SidebarController : BaseController
    {
        private readonly IRepository<BlogPost> blogPosts;
        private readonly IRepository<Tag> tags;

        public SidebarController(IRepository<BlogPost> blogPosts, IRepository<Tag> tags)
        {
            this.blogPosts = blogPosts;
            this.tags = tags;
        }

        [ChildActionOnly]
        [OutputCache(Duration = 10 * 60)]
        public ActionResult Index()
        {
            var model = new SidebarViewModel();
            model.RecentPosts = this.Cache.Get(
                "RecentBlogPosts",
                () =>
                this.blogPosts.All()
                    .OrderByDescending(x => x.CreatedOn)
                    .Project()
                    .To<RecentBlogPostViewModel>()
                    .Take(5)
                    .ToList(),
                600);

            model.Tags = this.tags.All().Project().To<TagViewModel>().OrderByDescending(x => x.PostsCount).ToList();

            model.RecentVideos = this.Cache.Get(
                "RecentVideos",
                () =>
                    {
                        if (string.IsNullOrWhiteSpace(ConfigurationManager.AppSettings["YouTubeApiKey"]))
                        {
                            return new List<VideoListItemViewModel>();
                        }

                        return
                            new LatestVideosProvider(ConfigurationManager.AppSettings["YouTubeApiKey"]).GetLatestVideos(
                                5,
                                "UULC-vbm7OWvpbqzXaoAMGGw").Project().To<VideoListItemViewModel>().ToList();
                    },
                7200);

            return this.PartialView("_SidebarPartial", model);
        }
    }
}

BlogSystem.Web/Views/Shared/_ImageOrVideo.cshtml
@model BlogSystem.Web.ViewModels.Home.BlogPostAnnotationViewModel

@if (Model.ImageOrVideoUrl != null)
{
    <div class="blog-img">
        @if (Model.ImageOrVideoUrl.Contains("youtube.com"))
        {
            <div class="responsive-video">
                <iframe src="@Model.ImageOrVideoUrl" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
        }
        else
        {
            <img src="@Model.ImageOrVideoUrl" class="img-responsive" alt="@Model.Title" />
        }
    </div>
}

BlogSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <title>@ViewBag.Title - @ViewBag.Settings.Get["Home Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="@ViewBag.Settings.Get["Keywords"], @ViewBag.Keywords" />
    @if (!string.IsNullOrWhiteSpace(ViewBag.Description))
    {
        <meta name="description" content="@ViewBag.Description" />
    }
    <meta name="robots" content="index, follow" />
    <meta name="revisit-after" content="1 days" />
    <meta name="author" content="@ViewBag.Settings.Get["Author"]" />
    <meta name="generator" content="Nikolay.IT BlogSystem - https://github.com/NikolayIT/BlogSystem" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="alternate" type="application/rss+xml" title="Blog RSS" href="/RSS/Blog" />
    @Styles.Render("~/Content/css")
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-25135627-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body class="boxed-layout container">
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=290972921054347&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <div class="wrapper">
        <header class="header">
            <div class="row">
                <div class="col-md-6">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">
                            <img id="logo-header" src="@ViewBag.Settings.Get["Logo URL"]" width="300" height="80" alt="Logo">
                        </a>
                    </div>
                </div>

                <div class="navbar navbar-default col-md-6" role="navigation">
                    <div class="topbar">
                        @Html.Partial("_LoginPartial")
                    </div>
                    <div class="clearfix"></div>
                    <nav class="collapse navbar-collapse navbar-responsive-collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="/">Home</a></li>
                            @Html.Action("Menu", "Home", routeValues: new { Area = string.Empty })
                            <li><a href="/Videos">My Videos</a></li>
                            @if (User.IsAdmin())
                            {
                                @Html.Action("Menu", "Admin", routeValues: new { Area = "Administration" })
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <div class="breadcrumbs">
            <div class="container">
                <h1 class="pull-left">@ViewBag.Title</h1>
                @if (IsSectionDefined("breadcrumbs"))
                {
                    <ul class="pull-right breadcrumb">
                        @RenderSection("breadcrumbs", false)
                    </ul>
                }
            </div>
        </div>

        <div class="container content">
            <div class="row blog-page">
                <div class="col-md-9">
                    @RenderBody()
                </div>

                <!-- Right Sidebar -->
                <aside class="col-md-3 magazine-page">
                    @Html.Action("Index", "Sidebar", routeValues: new { area = string.Empty })
                </aside>
                <!-- End Right Sidebar -->
            </div>
        </div>

        <footer class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p>&copy; 2011-@DateTime.Now.Year <strong>@ViewBag.Settings.Get["Blog Name"]</strong> Brought to you by <a href="https://www.google.com/search?q=Magic+Unicorns&tbm=isch" target="_blank"><i class="fa fa-magic"></i>Magic Unicorns</a></p>
                    </div>
                    <div class="col-md-6">
                        <p class="pull-right"><a href="https://github.com/NikolayIT/BlogSystem" target="_blank"><i class="fa fa-github"></i>Open Source System <i class="fa fa-smile-o"></i></a> ver. 20150618.9ebe6ff</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BlogSystem.Web/Views/Shared/_Menu.cshtml
@model IEnumerable<BlogSystem.Web.ViewModels.Home.MenuItemViewModel>

@foreach (var menuItem in Model)
{
    <li><a href="/Pages/@menuItem.Permalink">@menuItem.Title</a></li>
}

BlogSystem.Web/Views/Shared/_PageLoginPartial.cshtml
<div>
    @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "btn-u" })
    @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "btn-u" })
</div>

BlogSystem.Web/Views/Shared/_SidebarPartial.cshtml
@model SidebarViewModel

@*<!-- Search Bar -->
    <div class="headline headline-md"><h2>Search</h2></div>
    <div class="input-group margin-bottom-40">
        <input type="text" class="form-control" placeholder="Search">
        <span class="input-group-btn">
            <button class="btn-u" type="button">Go</button>
        </span>
    </div>
    <!-- End Search Bar -->*@

<!-- Social Bar -->
<div class="headline headline-md">
    <h2>Social?</h2>
</div>
<ul class="list-unstyled blog-photos margin-bottom-30">
    <li><a href="@ViewBag.Settings.Get["GitHub Profile"]" target="_blank"><i class="fa fa-github hover-effect"></i></a></li>
    <li><a href="@ViewBag.Settings.Get["Stack Overflow Profile"]" target="_blank"><i class="fa fa-stack-overflow hover-effect"></i></a></li>
    <li><a href="@ViewBag.Settings.Get["Linked In Profile"]" target="_blank"><i class="fa fa-linkedin-square hover-effect"></i></a></li>
    <li><a href="mailto:@ViewBag.Settings.Get["Contact Email"]" target="_blank" rel="nofollow"><i class="fa fa-envelope hover-effect"></i></a></li>
    <li><a href="@ViewBag.Settings.Get["Facebook Profile"]" target="_blank"><i class="fa fa-facebook-square hover-effect"></i></a></li>
    <li><a href="@ViewBag.Settings.Get["Foursquare Profile"]" target="_blank"><i class="fa fa-foursquare hover-effect"></i></a></li>
    <li><a href="@ViewBag.Settings.Get["Google Profile"]" target="_blank"><i class="fa fa-google-plus-square hover-effect"></i></a></li>
    <li><a href="@ViewBag.Settings.Get["RSS Url"]" target="_blank"><i class="fa fa-rss-square hover-effect"></i></a></li>
</ul>
<!-- End Social -->
<!-- GitHub Badge -->
<div class="headline headline-md">
    <h2>Me @@GitHub</h2>
</div>
@Html.Raw(ViewBag.Settings.Get["GitHub Badge HTML Code"])
<!-- End GitHub Badge -->
<!-- StackOverflow Badge -->
@if (ViewBag.Settings.Get.ContainsKey("StackOverflow Badge HTML Code"))
{
    <div class="headline headline-md">
        <h2>Me @@StackOverflow</h2>
    </div>
    @Html.Raw(ViewBag.Settings.Get["StackOverflow Badge HTML Code"])
}
<!-- End StackOverflow Badge -->

<!-- Videos -->
<div class="posts margin-bottom-40">
    <div class="headline headline-md">
        <h2>Recent Videos</h2>
    </div>
    @foreach (BlogSystem.Web.ViewModels.Videos.VideoListItemViewModel video in Model.RecentVideos)
    {
        <dl class="dl-horizontal">
            <dt>
                <a href="@video.VideoUrl" target="_blank">
                    <img src="@video.SmallThumbnailUrl" alt="@video.Title" title="@video.Description" width="60" height="60" />
                </a>
            </dt>
            <dd>
                <p>
                    <a href="@video.VideoUrl">@video.Title</a>
                </p>
            </dd>
        </dl>
    }
</div>
<!-- End videos -->

<!-- Posts -->
<div class="posts margin-bottom-40">
    <div class="headline headline-md">
        <h2>Recent Posts</h2>
    </div>
    @foreach (RecentBlogPostViewModel post in Model.RecentPosts)
    {
        <dl class="dl-horizontal">
            <dt><a href="@post.Url"><i class="fa @post.IconClass"></i></a></dt>
            <dd>
                <p>
                    <a href="@post.Url">@post.Title</a>
                </p>
            </dd>
        </dl>
    }
</div>
<!-- End posts -->